# TODO Take default and overwrite with profile. Set option empty to overwrite.
# TODO? Optionally have multiple identifiers per priority level?

[default]
name = "default"
identifiers = ["TODO"] # sscs: skip
denied_extensions = [ ".log",]
denied_files = [ "todo.txt",]
denied_directories = [ ".git",]

[rust]
name = "rust"
identifiers = ["FIXME", "TODO", "TODO?", "UPSTREAM"] # sscs: skip
indicator_files = [ "Cargo.toml", "Cargo.lock",]
denied_extensions = [ ".log",]
denied_files = [ "todo.txt",]
denied_directories = [ "target", ".git",]

[python]
name = "python"
identifiers = ["FIXME", "TODO", "TODO?", "UPSTREAM"] # sscs: skip
indicator_files = [ "pyproject.toml", "Pipfile", "setup.py",]
denied_extensions = [ ".log",]
denied_files = [ "todo.txt",]
denied_directories = [ ".git", ".mypy_cache", ".venv",]

[webdev]
name = "webdev"
identifiers = ["FIXME", "TODO", "TODO?", "UPSTREAM"] # sscs: skip
indicator_files = [ "package.json", "tsconfig.json", ".eslintrc.json",]
denied_extensions = [ ".log", ".js"]
denied_files = [ "todo.txt",]
denied_directories = [ ".git", ".mypy_cache", ".venv", "node_modules"]
